In [ ]:
### Trades

In [1]:
import pandas as pd

In [4]:
source_data = pd.read_csv("./Day3/Day3_Lab_Environment/data/trade_blotter.csv")

In [3]:
source_data.head(5)

,trade_id,trade_date,security_id,trader_id,trade_type,quantity,price,last_modified_ts
0,100224,2026-05-19,1,6,SELL,500,1155.56,2026-05-19 17:43:00
1,100137,2026-05-13,2,4,BUY,4200,2688.04,2026-05-13 16:59:00
2,100112,2026-05-11,5,6,BUY,4100,2798.81,2026-05-11 16:06:00
3,100496,2026-06-09,8,2,BUY,4000,2038.49,2026-06-09 12:41:00
4,100254,2026-05-22,5,1,BUY,1900,1238.77,2026-05-22 09:55:00

In [5]:
source_data['trade_value'] = source_data['quantity'] * source_data['price']

In [6]:
source_data.head(5)

,trade_id,trade_date,security_id,trader_id,trade_type,quantity,price,last_modified_ts,trade_value
0,100224,2026-05-19,1,6,SELL,500,1155.56,2026-05-19 17:43:00,577780.0
1,100137,2026-05-13,2,4,BUY,4200,2688.04,2026-05-13 16:59:00,11289768.0
2,100112,2026-05-11,5,6,BUY,4100,2798.81,2026-05-11 16:06:00,11475121.0
3,100496,2026-06-09,8,2,BUY,4000,2038.49,2026-06-09 12:41:00,8153960.0
4,100254,2026-05-22,5,1,BUY,1900,1238.77,2026-05-22 09:55:00,2353663.0

In [7]:
source_data['trade_value'].sum()

np.float64(3351976785.0)

In [8]:
source_data.to_csv('updated_trades_data.csv')

In [10]:
source_data.shape

(567, 9)

In [17]:
type(source_data['trade_type'][0]).

str

In [18]:
source_data.dtypes

trade_id              int64
trade_date           object
security_id           int64
trader_id             int64
trade_type           object
quantity              int64
price               float64
last_modified_ts     object
trade_value         float64
dtype: object

In [ ]:
# source_data